In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('Combined-780 - Sheet1.csv')
data

Signal   Mean (µV)     RMS (µV)     MRS (µV)  Zero Crossings  \
0        e1.1 -111.543263   165.326922   137.464510               6   
1        e1.2  -85.046038   140.633143   111.886389               6   
2        e1.3  -46.838299   126.812428    85.819704              16   
3        e1.4  -47.013536   143.652350    91.850550               7   
4        e1.5  -15.339653   113.011520    53.273050              24   
..        ...         ...          ...          ...             ...   
775  e47.1.16 -492.032900   791.292300   693.099200               3   
776  e47.1.17 -255.891500   455.610800   378.904600               4   
777  e47.1.18  224.316200   619.768200   541.530000               8   
778  e47.1.19 -164.945500   986.025200   798.400200               4   
779  e47.1.20 -385.829500  1501.861800  1148.949700               3   

     Frequency (Hz)  Delta (µV² /Hz)  Theta (µV² /Hz)  Alpha (µV² /Hz)  \
0               3.0        13.871195         0.216515         0.157400   
1               3.0         5.126801         0.176441         0.151454   
2               8.0         1.261876         0.181805         0.161871   
3               3.5         0.899144         0.212408         0.298429   
4              12.0         0.423585         0.195163         0.150992   
..              ...              ...              ...              ...   
775             1.5        34.918747         2.114091         0.244951   
776             2.0        15.347951         1.263933         0.188982   
777             4.0        24.577597         0.953114         0.249922   
778             2.0        31.002390         1.905827         0.262337   
779             1.5        63.294042         3.625288         0.130177   

     Beta (µV² /Hz)  Gamma (µV² /Hz)  Label  
0          0.471267         0.360638      0  
1          0.471898         0.364846      0  
2          0.472354         0.372668      0  
3          0.738894         0.501854      0  
4          0.484105         0.371071      0  
..              ...              ...    ...  
775        0.139495         0.062960      1  
776        0.112097         0.051938      1  
777        0.139794         0.061432      1  
778        0.121908         0.053995      1  
779        0.113923         0.049579      1  

[780 rows x 12 columns]

In [6]:
X = data.drop(columns=['Signal','Label'])
y = data['Label']

In [7]:
import numpy as np
np.isnan(X).any()

Mean (µV)          False
RMS (µV)           False
MRS (µV)           False
Zero Crossings     False
Frequency (Hz)     False
Delta (µV² /Hz)    False
Theta (µV² /Hz)    False
Alpha (µV² /Hz)    False
Beta (µV² /Hz)     False
Gamma (µV² /Hz)    False
dtype: bool

In [8]:
X.loc[[2,3,4,50]]
from sklearn.metrics import confusion_matrix

In [9]:
from sklearn.model_selection import KFold
from sklearn import svm
from sklearn import preprocessing as pre

kf = KFold(n_splits=7)
acc = []
sens = []
spec = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    model = svm.SVC(kernel='linear',C=20).fit(X_train_scaled, y_train)
    score = model.score(X_test_scaled, y_test)
    y_pred = model.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
    sens.append(sensitivity1)
    spec.append(specificity1)
    
print(max(acc))

Confusion Matrix : 
 [[63 29]
 [ 6 14]]
Accuracy :  0.6875
Sensitivity :  0.6847826086956522
Specificity :  0.7
Confusion Matrix : 
 [[36 32]
 [32 12]]
Accuracy :  0.42857142857142855
Sensitivity :  0.5294117647058824
Specificity :  0.2727272727272727
Confusion Matrix : 
 [[34  2]
 [72  4]]
Accuracy :  0.3392857142857143
Sensitivity :  0.9444444444444444
Specificity :  0.05263157894736842
Confusion Matrix : 
 [[41  3]
 [ 9 58]]
Accuracy :  0.8918918918918919
Sensitivity :  0.9318181818181818
Specificity :  0.8656716417910447
Confusion Matrix : 
 [[50 28]
 [ 6 27]]
Accuracy :  0.6936936936936937
Sensitivity :  0.6410256410256411
Specificity :  0.8181818181818182
Confusion Matrix : 
 [[44  7]
 [38 22]]
Accuracy :  0.5945945945945946
Sensitivity :  0.8627450980392157
Specificity :  0.36666666666666664
Confusion Matrix : 
 [[63  8]
 [29 11]]
Accuracy :  0.6666666666666666
Sensitivity :  0.8873239436619719
Specificity :  0.275
0.8918918918918919


In [10]:
from sklearn.neighbors import KNeighborsClassifier

kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    knn = KNeighborsClassifier(n_neighbors=5).fit(X_train_scaled, y_train)
    score = knn.score(X_test_scaled, y_test)
    y_pred = knn.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)

# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[21 57]
 [ 9 11]]
Accuracy :  0.32653061224489793
Sensitivity :  0.2692307692307692
Specificity :  0.55
Confusion Matrix : 
 [[33 25]
 [14 26]]
Accuracy :  0.6020408163265306
Sensitivity :  0.5689655172413793
Specificity :  0.65
Confusion Matrix : 
 [[18  6]
 [40 34]]
Accuracy :  0.5306122448979592
Sensitivity :  0.75
Specificity :  0.4594594594594595
Confusion Matrix : 
 [[28 32]
 [23 15]]
Accuracy :  0.4387755102040816
Sensitivity :  0.4666666666666667
Specificity :  0.39473684210526316
Confusion Matrix : 
 [[15 34]
 [25 23]]
Accuracy :  0.3917525773195876
Sensitivity :  0.30612244897959184
Specificity :  0.4791666666666667
Confusion Matrix : 
 [[47  4]
 [16 30]]
Accuracy :  0.7938144329896907
Sensitivity :  0.9215686274509803
Specificity :  0.6521739130434783
Confusion Matrix : 
 [[29 34]
 [10 24]]
Accuracy :  0.5463917525773195
Sensitivity :  0.4603174603174603
Specificity :  0.7058823529411765
Confusion Matrix : 
 [[45 12]
 [28 12]]
Accuracy :  0.587628865979

In [11]:
from sklearn.neighbors import KNeighborsClassifier
kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    knn = KNeighborsClassifier(n_neighbors=10).fit(X_train_scaled, y_train)
    score = knn.score(X_test_scaled, y_test)
    y_pred = knn.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)

# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[25 53]
 [12  8]]
Accuracy :  0.336734693877551
Sensitivity :  0.32051282051282054
Specificity :  0.4
Confusion Matrix : 
 [[36 22]
 [19 21]]
Accuracy :  0.5816326530612245
Sensitivity :  0.6206896551724138
Specificity :  0.525
Confusion Matrix : 
 [[22  2]
 [45 29]]
Accuracy :  0.5204081632653061
Sensitivity :  0.9166666666666666
Specificity :  0.3918918918918919
Confusion Matrix : 
 [[37 23]
 [26 12]]
Accuracy :  0.5
Sensitivity :  0.6166666666666667
Specificity :  0.3157894736842105
Confusion Matrix : 
 [[23 26]
 [25 23]]
Accuracy :  0.4742268041237113
Sensitivity :  0.46938775510204084
Specificity :  0.4791666666666667
Confusion Matrix : 
 [[46  5]
 [18 28]]
Accuracy :  0.7628865979381443
Sensitivity :  0.9019607843137255
Specificity :  0.6086956521739131
Confusion Matrix : 
 [[40 23]
 [17 17]]
Accuracy :  0.5876288659793815
Sensitivity :  0.6349206349206349
Specificity :  0.5
Confusion Matrix : 
 [[47 10]
 [32  8]]
Accuracy :  0.5670103092783505
Sensitivity :

In [12]:
from sklearn.linear_model import LogisticRegression

kf = KFold(n_splits=8)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    mod = LogisticRegression(random_state=0,max_iter=1000).fit(X_train_scaled, y_train)
    score = mod.score(X_test_scaled, y_test)
    y_pred = mod.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[45 33]
 [ 9 11]]
Accuracy :  0.5714285714285714
Sensitivity :  0.5769230769230769
Specificity :  0.55
Confusion Matrix : 
 [[40 18]
 [26 14]]
Accuracy :  0.5510204081632653
Sensitivity :  0.6896551724137931
Specificity :  0.35
Confusion Matrix : 
 [[ 4 20]
 [50 24]]
Accuracy :  0.2857142857142857
Sensitivity :  0.16666666666666666
Specificity :  0.32432432432432434
Confusion Matrix : 
 [[41 19]
 [25 13]]
Accuracy :  0.5510204081632653
Sensitivity :  0.6833333333333333
Specificity :  0.34210526315789475
Confusion Matrix : 
 [[39 10]
 [25 23]]
Accuracy :  0.6391752577319587
Sensitivity :  0.7959183673469388
Specificity :  0.4791666666666667
Confusion Matrix : 
 [[49  2]
 [16 30]]
Accuracy :  0.8144329896907216
Sensitivity :  0.9607843137254902
Specificity :  0.6521739130434783
Confusion Matrix : 
 [[42 21]
 [19 15]]
Accuracy :  0.5876288659793815
Sensitivity :  0.6666666666666666
Specificity :  0.4411764705882353
Confusion Matrix : 
 [[48  9]
 [29 11]]
Accuracy :  

In [13]:
from sklearn import tree

kf = KFold(n_splits=10)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    clf = tree.DecisionTreeClassifier().fit(X_train_scaled, y_train)
    score = clf.score(X_test_scaled, y_test)
    acc.append(score)
    y_pred = clf.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(accuracy1)
#     sens.append(sensitivity1)
#     spec.append(specificity1)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[18 42]
 [11  7]]
Accuracy :  0.32051282051282054
Sensitivity :  0.3
Specificity :  0.3888888888888889
Confusion Matrix : 
 [[ 1 39]
 [10 28]]
Accuracy :  0.3717948717948718
Sensitivity :  0.025
Specificity :  0.7368421052631579
Confusion Matrix : 
 [[19 41]
 [ 5 13]]
Accuracy :  0.41025641025641024
Sensitivity :  0.31666666666666665
Specificity :  0.7222222222222222
Confusion Matrix : 
 [[12  0]
 [56 10]]
Accuracy :  0.28205128205128205
Sensitivity :  1.0
Specificity :  0.15151515151515152
Confusion Matrix : 
 [[33 15]
 [29  1]]
Accuracy :  0.4358974358974359
Sensitivity :  0.6875
Specificity :  0.03333333333333333
Confusion Matrix : 
 [[ 7 21]
 [18 32]]
Accuracy :  0.5
Sensitivity :  0.25
Specificity :  0.64
Confusion Matrix : 
 [[35 23]
 [ 0 20]]
Accuracy :  0.7051282051282052
Sensitivity :  0.603448275862069
Specificity :  1.0
Confusion Matrix : 
 [[23 11]
 [ 0 44]]
Accuracy :  0.8589743589743589
Sensitivity :  0.6764705882352942
Specificity :  1.0
Confusion M

In [14]:
from sklearn.neural_network import MLPClassifier

kf = KFold(n_splits=10)
acc = []
for train_index, test_index in kf.split(X,y):
    # print("%s %s" % (train_index, test_index))
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y.loc[train_index], y.loc[test_index]
    X_train_scaled = pre.scale(X_train)
    X_test_scaled = pre.scale(X_test)
    clf = MLPClassifier(random_state=0, max_iter=5000, alpha=0.001, hidden_layer_sizes=(10,2)).fit(X_train_scaled, y_train)
    score = clf.score(X_test_scaled, y_test)
    y_pred = clf.predict(X_test_scaled)
    cm1 = confusion_matrix(y_test, y_pred)
    print('Confusion Matrix : \n', cm1)

    total1=sum(sum(cm1))
    #####from confusion matrix calculate accuracy
    accuracy1=(cm1[0,0]+cm1[1,1])/total1
    print ('Accuracy : ', accuracy1)

    sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
    print('Sensitivity : ', sensitivity1 )

    specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
    print('Specificity : ', specificity1)
    acc.append(score)
    
# mean_acc = sum(acc)/len(acc)
# mean_sens = sum(sens)/len(sens)
# mean_spec = sum(spec)/len(spec)
print(max(acc))

Confusion Matrix : 
 [[30 30]
 [ 3 15]]
Accuracy :  0.5769230769230769
Sensitivity :  0.5
Specificity :  0.8333333333333334
Confusion Matrix : 
 [[23 17]
 [22 16]]
Accuracy :  0.5
Sensitivity :  0.575
Specificity :  0.42105263157894735
Confusion Matrix : 
 [[39 21]
 [11  7]]
Accuracy :  0.5897435897435898
Sensitivity :  0.65
Specificity :  0.3888888888888889
Confusion Matrix : 
 [[11  1]
 [56 10]]
Accuracy :  0.2692307692307692
Sensitivity :  0.9166666666666666
Specificity :  0.15151515151515152
Confusion Matrix : 
 [[41  7]
 [26  4]]
Accuracy :  0.5769230769230769
Sensitivity :  0.8541666666666666
Specificity :  0.13333333333333333
Confusion Matrix : 
 [[27  1]
 [10 40]]
Accuracy :  0.8589743589743589
Sensitivity :  0.9642857142857143
Specificity :  0.8
Confusion Matrix : 
 [[42 16]
 [16  4]]
Accuracy :  0.5897435897435898
Sensitivity :  0.7241379310344828
Specificity :  0.2
Confusion Matrix : 
 [[29  5]
 [22 22]]
Accuracy :  0.6538461538461539
Sensitivity :  0.8529411764705882
Specif