In [16]:
import pandas as pd

In [17]:
training = pd.read_csv('Combined-780 - Sheet1.csv')
training

Signal   Mean (µV)     RMS (µV)     MRS (µV)  Zero Crossings  \
0        e1.1 -111.543263   165.326922   137.464510               6   
1        e1.2  -85.046038   140.633143   111.886389               6   
2        e1.3  -46.838299   126.812428    85.819704              16   
3        e1.4  -47.013536   143.652350    91.850550               7   
4        e1.5  -15.339653   113.011520    53.273050              24   
..        ...         ...          ...          ...             ...   
775  e47.1.16 -492.032900   791.292300   693.099200               3   
776  e47.1.17 -255.891500   455.610800   378.904600               4   
777  e47.1.18  224.316200   619.768200   541.530000               8   
778  e47.1.19 -164.945500   986.025200   798.400200               4   
779  e47.1.20 -385.829500  1501.861800  1148.949700               3   

     Frequency (Hz)  Delta (µV² /Hz)  Theta (µV² /Hz)  Alpha (µV² /Hz)  \
0               3.0        13.871195         0.216515         0.157400   
1               3.0         5.126801         0.176441         0.151454   
2               8.0         1.261876         0.181805         0.161871   
3               3.5         0.899144         0.212408         0.298429   
4              12.0         0.423585         0.195163         0.150992   
..              ...              ...              ...              ...   
775             1.5        34.918747         2.114091         0.244951   
776             2.0        15.347951         1.263933         0.188982   
777             4.0        24.577597         0.953114         0.249922   
778             2.0        31.002390         1.905827         0.262337   
779             1.5        63.294042         3.625288         0.130177   

     Beta (µV² /Hz)  Gamma (µV² /Hz)  Label  
0          0.471267         0.360638      0  
1          0.471898         0.364846      0  
2          0.472354         0.372668      0  
3          0.738894         0.501854      0  
4          0.484105         0.371071      0  
..              ...              ...    ...  
775        0.139495         0.062960      1  
776        0.112097         0.051938      1  
777        0.139794         0.061432      1  
778        0.121908         0.053995      1  
779        0.113923         0.049579      1  

[780 rows x 12 columns]

In [18]:
X_train = training.drop(columns=['Signal','Label'])
y_train = training['Label']

In [19]:
from sklearn import preprocessing as pre
X_train_scaled = pre.scale(X_train)
X_train_scaled.shape

(780, 10)

In [34]:
X_test = test.drop(columns=['Signal','Label'])
y_test = test['Label'][20:30]
X_test_scaled = pre.scale(X_test)[20:30]

In [21]:
X_test.shape

(780, 10)

In [22]:
X_train_scaled.shape

(780, 10)

In [23]:
import numpy as np
np.isnan(X_train_scaled).any()
# np.where(X_train.values >= np.finfo(np.float64).max)

False

In [24]:
X_train.columns

Index(['Mean (µV)', 'RMS (µV)', 'MRS (µV)', 'Zero Crossings', 'Frequency (Hz)',
       'Delta (µV² /Hz)', 'Theta (µV² /Hz)', 'Alpha (µV² /Hz)',
       'Beta (µV² /Hz)', 'Gamma (µV² /Hz)'],
      dtype='object')

In [25]:
# import numpy as np
# from sklearn.model_selection import KFold

# kf = KFold(n_splits=10)
# for train_index, test_index in kf.split(X):
#     print("%s %s" % (train_index, test_index))
#     X_train, X_test = X[train_index], X[test_index]
#     y_train, y_test = y[train_index], y[test_index]

In [26]:
from sklearn.metrics import confusion_matrix
from sklearn import svm
model = svm.SVC().fit(X_train_scaled, y_train)
model.score(X_test_scaled, y_test)
y_pred = model.predict(X_test_scaled)
cm1 = confusion_matrix(y_test, y_pred)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)

Confusion Matrix : 
 [[9 1]
 [0 0]]
Accuracy :  0.9
Sensitivity :  0.9
Specificity :  nan


C:\Users\Yash Srivastava\AppData\Local\Temp\ipykernel_3212\1624536295.py:17: RuntimeWarning: invalid value encountered in scalar divide
  specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])


In [27]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=10).fit(X_train_scaled, y_train)
knn.score(X_test_scaled, y_test)
y_pred = knn.predict(X_test_scaled)
cm1 = confusion_matrix(y_test, y_pred)
# cm1 = confusion_matrix(Fiber_df[['active_cust']],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)

Confusion Matrix : 
 [[9 1]
 [0 0]]
Accuracy :  0.9
Sensitivity :  0.9
Specificity :  nan


C:\Users\Yash Srivastava\AppData\Local\Temp\ipykernel_3212\3609656283.py:17: RuntimeWarning: invalid value encountered in scalar divide
  specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])


In [28]:
from sklearn.linear_model import LogisticRegression
mod = LogisticRegression(random_state=0,max_iter=1000).fit(X_train_scaled, y_train)
print(mod.score(X_test_scaled, y_test))
y_pred = mod.predict(X_test_scaled)
cm1 = confusion_matrix(y_test, y_pred)
# cm1 = confusion_matrix(Fiber_df[['active_cust']],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)

0.7
Confusion Matrix : 
 [[7 3]
 [0 0]]
Accuracy :  0.7
Sensitivity :  0.7
Specificity :  nan


C:\Users\Yash Srivastava\AppData\Local\Temp\ipykernel_3212\4120903834.py:17: RuntimeWarning: invalid value encountered in scalar divide
  specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])


In [29]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train_scaled, y_train)
clf.score(X_test_scaled, y_test)
# y_pred = clf.predict(X_test)
# cm1 = confusion_matrix(y_test, y_pred)
# # cm1 = confusion_matrix(Fiber_df[['active_cust']],predicted_class1)
# print('Confusion Matrix : \n', cm1)

# print(clf.score(X_test, y_test))
# total1=sum(sum(cm1))
# #####from confusion matrix calculate accuracy
# accuracy1=(cm1[0,0]+cm1[1,1])/total1
# print ('Accuracy : ', accuracy1)

# sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
# print('Sensitivity : ', sensitivity1 )

# specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
# print('Specificity : ', specificity1)
# print(clf.max_depth)

1.0

In [30]:
# 70.99 - dtree - varies a lot
# 60.99 - lr - fixed
# 63 - knn - fixed
# 40 - svm - fixed

In [31]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(random_state=0, max_iter=2000).fit(X_train_scaled, y_train)
clf.score(X_test_scaled, y_test)
y_pred = clf.predict(X_test_scaled)
cm1 = confusion_matrix(y_test, y_pred)
# cm1 = confusion_matrix(Fiber_df[['active_cust']],predicted_class1)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('Sensitivity : ', sensitivity1 )

specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Specificity : ', specificity1)

Confusion Matrix : 
 [[9 1]
 [0 0]]
Accuracy :  0.9
Sensitivity :  0.9
Specificity :  nan


C:\Users\Yash Srivastava\AppData\Local\Temp\ipykernel_3212\489008940.py:17: RuntimeWarning: invalid value encountered in scalar divide
  specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])


In [32]:
X_train_scaled[:,:2].shape

(780, 2)

In [33]:
# import numpy as np
# import matplotlib.pyplot as plt
# from matplotlib.colors import ListedColormap
# from sklearn import neighbors, datasets

# n_neighbors = 10

# # import some data to play with
# # iris = datasets.load_iris()

# # we only take the first two features. We could avoid this ugly
# # slicing by using a two-dim dataset
# # X = iris.data[:, :2]
# # y = iris.target

# X = X_train_scaled
# y = y_train

# h = .02  # step size in the mesh

# # Create color maps
# cmap_light = ListedColormap(['orange', 'cyan', 'cornflowerblue'])
# cmap_bold = ListedColormap(['darkorange', 'c', 'darkblue'])

# for weights in ['uniform', 'distance']:
#     # we create an instance of Neighbours Classifier and fit the data.
#     clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
#     clf.fit(X, y)

#     # Plot the decision boundary. For that, we will assign a color to each
#     # point in the mesh [x_min, x_max]x[y_min, y_max].
#     x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
#     y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
#     xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
#                          np.arange(y_min, y_max, h))
#     Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

#     # Put the result into a color plot
#     Z = Z.reshape(xx.shape)
#     plt.figure()
#     plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

#     # Plot also the training points
#     plt.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_bold,
#                 edgecolor='k', s=20)
#     plt.xlim(xx.min(), xx.max())
#     plt.ylim(yy.min(), yy.max())
#     plt.title("2-Class classification (k = %i, weights = '%s')"
#               % (n_neighbors, weights))

# plt.show()